DROP TABLE IF EXISTS vehicleinfo;

CREATE TABLE vehicleinfo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    StockNumber INTEGER NOT NULL,
    Registration TEXT NOT NULL,
    VinNumber TEXT NOT NULL,
	ChassisNumber TEXT NOT NULL,
	Manufacturer TEXT NOT NULL,
	Model TEXT NOT NULL,
	ModelDetail TEXT NOT NULL,
	YEAR INTEGER NOT NULL,
	Odometer TEXT NOT NULL,
	CCRating TEXT NOT NULL,
	Type TEXT NOT NULL,
	FuelType TEXT NOT NULL,
	Transmission TEXT NOT NULL,
	Seats TEXT NOT NULL,
	ExternalColour TEXT NOT NULL,
	IsNew TEXT NOT NULL,
	InTransit TEXT NOT NULL,
	HasWOF TEXT NOT NULL,
	ApplyStandardText TEXT NOT NULL,
	Features TEXT NOT NULL,
	Comment TEXT NOT NULL,
	RetailPrice TEXT NOT NULL,
	ImageIndexList TEXT NOT NULL,
	ORCIncluded TEXT NOT NULL,
	SubTitle TEXT NOT NULL,
	YouTubeURL TEXT NOT NULL,
	CleanCarMode TEXT NOT NULL,
	CleanCarAmount INTEGER NOT NULL,
	CleanCarAmountMax INTEGER NOT NULL,
	CleanVehicleDisclaimerLong TEXT NOT NULL,
	OrcAmount TEXT NOT NULL,
	CleanCarInd TEXT NOT NULL,
	SafetyRating TEXT NOT NULL,
	SafetyTest TEXT NOT NULL,
	FuelSaverRating TEXT NOT NULL,
	FuelEconomy TEXT NOT NULL,
	FuelEconomyText TEXT NOT NULL,
	AnnFuelCostText TEXT NOT NULL,
	Co2Rating TEXT NOT NULL,
	Co2 INTEGER NOT NULL,
	YearlyCo2 TEXT NOT NULL,
	PollutantsRating INTEGER NOT NULL,
	PollutantsTestRegime TEXT NOT NULL
);